### ISSUE TITLE
Index.js issue

### ISSUE THREAD

**Issue by shobiraj** [brightcove/Adobe-AEM-Brightcove-Connector#2]
Hi , while configuring the AEM brightcove connector.I’m  getting an error on index.js  404 error. Do anyone have got the same error? Any ideas how this can be resolved? First it support AEM 6.5

**Comment by hngrylobster** [comment]
Hi @shobiraj - are you seeing incorrect/broken functionality or just a 404 message in the console? If you are experiencing the former, please submit a support ticket. Also, please make sure your user is in the `administrators` group.

**Comment by shobiraj** [comment]
> Hi @shobiraj - are you seeing incorrect/broken functionality or just a 404 message in the console? If you are experiencing the former, please submit a support ticket. Also, please make sure your user is in the `administrators` group.

It worked after creating the user group! But still we have index js file showing up on console.
