### ISSUE TITLE
BrightCove Certificates

### ISSUE THREAD

**Issue by surenderkanaveni** [brightcove/Adobe-AEM-Brightcove-Connector#31]
HI Team,

Could you please let me know where can i get below brightcove certificates. Without these certs I can see sync is not happening between AEM and BrightCove. I have tried to export the certs from URL but it didnt work.

"https://players.api.brightcove.com/v2:::D:/cert/players_api.cer",
"https://cms.api.brightcove.com/v1:::D:/cert/cms_api.cer",
"https://ingest.api.brightcove.com/v1:::D:/cert/ingest_api.cer",
"https://oauth.brightcove.com/v4/access_token:::D:/cert/oath_brightcove.cer"

**Comment by apadhye** [comment]
Hi Surender, 

Thanks for the question. Have you followed all the [configuration steps](https://integrations.support.brightcove.com/adobe/adobe-aem-brightcove-connector-configuration.html) for the AEM Brightcove connector? Step 16 specifically talks about [Managing API credentials](https://apis.support.brightcove.com/general/managing-api-authentication-credentials.html). Once this is set up, you should have no problem pulling down the required certificates.

Have a great day!

**Comment by surenderkanaveni** [comment]
HI apadhye,

Thank you for the response. Yes In case if i enable enabled trust certificates as YES then I am seeing the error with the certificates. With default setting NO it's working fine.

Also within our company network I am seeing below error. Can you please let me know which certificate and how I need to pass to resolve the SSLHandshakeException issue ?


2021-05-13 02:22:59.566 INFO [com.coresecure.brightcove.wrapper.utils.HttpServices] executePost: https://oauth.brightcove.com/v4/access_token
2021-05-13 02:22:59.567 INFO [com.coresecure.brightcove.wrapper.webservices.BrcApi] getServices
2021-05-13 02:22:59.568 INFO [com.coresecure.brightcove.wrapper.utils.HttpServices] executePost: https://oauth.brightcove.com/v4/access_token
2021-05-13 02:22:59.882 ERROR [com.coresecure.brightcove.wrapper.utils.HttpServices] *** Connection Error * Check Connection / Proxy Configuration
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by apadhye** [comment]
Hi @surenderkanaveni,

Could you please provide more info on your setup? I am trying to figure out why you need the certificates because from my understanding of our APIs, we do not need individual certificates if the connector is correctly installed.

The errors above do not appear to be API errors. How does your network work? Are API calls sent through proxy servers or gateways? That could be the reason for the errors you see.

As a quick test, could you try getting your access tokens directly via Postman or Insomnia as mentioned in [this](https://apis.support.brightcove.com/oauth/guides/getting-access-tokens.html) doc? If this fails as well, then it points to a network issue and nothing to do with the AEM connector.

**Comment by surenderkanaveni** [comment]
Hi @apadhye 

Thanks for the response. Yes we are using proxy and it's not working within the proxy. If I disconnect to proxy then connection is working fine and I can see videos.

I am seeing below error with the proxy only. Do I have to install proxy certificate in brightcove ? I have added the proxy certificate in the java truststore but still I am seeing below errors.

com.coresecure.brightcove.wrapper.utils.HttpServices *** Connection Error * Check Connection / Proxy Configuration
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by apadhye** [comment]
This seems like a network issue and not something we can help with.
