### ISSUE TITLE
Synchronizing multilingual sub-folders with Brightcove connector

### ISSUE THREAD

**Issue by joestieg** [brightcove/Adobe-AEM-Brightcove-Connector#33]
We've set up sub-folders in our Brightcove directory for multilingual videos. (i.e. Spain, Germany, etc.) How can we modify the AEM Brightcove connector to sync metadata between Brightcove and AEM for these new sub-directories? Currently database synchronization is only working in the folder name with the numeric Account ID from the Brightcove configuration. We're also using version 5.5.4 of the Brightcove connector.
![screenshot](https://user-images.githubusercontent.com/39833188/127934603-4c0e5b6e-1827-402a-8a95-446c635551f3.png)

**Comment by hngrylobster** [comment]
This feature is under development and will be included in a future release this year.
