### ISSUE TITLE
Repository URL for dependency?

### ISSUE THREAD

**Issue by andres-holland** [brightcove/Adobe-AEM-Brightcove-Connector#34]
Hello!

I am trying to install the connector on an AEM Cloud instance through a CM pipeline. I've added the proper dependencies to the codebase, but what is the URL to the repository that holds this dependency?

I would assume it would be at the below link but it does not appear to be.

https://repo.maven.apache.org/maven2/com/brightcove/

Thanks.

**Comment by hngrylobster** [comment]
The package can be hosted in a private repository manager or if you are a Brightcove customer, please reach out to their support to get access to our hosted version.
