### ISSUE TITLE
Brightcove connector not working with AEM server running HTTPS

### ISSUE THREAD

**Issue by joestieg** [brightcove/Adobe-AEM-Brightcove-Connector#5]
We just switched to HTTPS on our AEM 6.4.8.2 author server and now we can no longer load the Brightcove admin page (version  5.5.4.). (see screenshot) Is there a setting that we need to change to have it work in HTTPS? Thanks.
![Capture](https://user-images.githubusercontent.com/39833188/111165775-cc49f980-8575-11eb-800c-354641ded08c.PNG)

**Comment by hngrylobster** [comment]
To better understand the issue, could you provide the following:
- Did anything else change besides the protocol (e.g. permissions, caching)?
- Do you see any error messages in Chrome's console?

**Comment by joestieg** [comment]
I'm not aware of any other changes. Also we see the following new error message in developer console. (the other two messages showed previously)
![capture2](https://user-images.githubusercontent.com/39833188/111193281-628b1900-8590-11eb-955b-77164e565736.PNG)

**Comment by hngrylobster** [comment]
It seems that something on the server is blocking that request from properly executing. Please file a ticket within the Brightcove support area so you can provide full client details and we can track this.

**Comment by joestieg** [comment]
I created the following ticket with Brightcove - 637377 

Thanks.
