### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by bjoernweide** [brightcove/Adobe-AEM-Brightcove-Connector#6]
Currently the source code contains 2 licenses - GPL and MIT (which is also linked for the Github repo). What license does apply (or is it dual-licensed? In any case some clarifying notes would be great!

**Comment by hngrylobster** [comment]
For these types of questions, please reach out to Brightcove support. However, we are cleaning up unclear license references in the next version and this repository is governed by an MIT license.
