### ISSUE TITLE
Using runmode for config settings instead of manual configuration

### ISSUE THREAD

**Issue by stiegjo** [brightcove/Adobe-AEM-Brightcove-Connector#62]
The Brightcove connector works when we configure the settings under /system/console/configMgr. However we would like to check the config settings into our code release by adding it under the runmode for config.author. Is it possible to add it to a runmode in the bundle instead of manually configuring it under the Web Console Configuration? The Brightcove Connector does not pick up the config settings from this location.

 i.e. ui.apps/src/main/content/jcr_root/apps/jhi-investments/config.author/ com.coresecure.brightcove.wrapper.sling.BrcServiceImpl.90abfe45-4b0c-41b0-b22b-b0ee9b79415f.config

**Comment by hngrylobster** [comment]
Yes, you should be able to deploy configurations just as you would for any other bundle and they will take effect within the connector.

**Comment by stiegjo** [comment]
I tried that but it's not getting picked up. Here's the format that I used in config:

`client_secret="XXXXXXXXXXXXXXX"
accountAlias="John\ Boy\ Investments"
client_id="xxxxxxxxx-xxxxx-xxxx-xxxxxxx-xxxxxxxxxxx"
defVideoPlayerID="default"
allowed_groups=["brightcove-authors"]
proxy=""
defPlaylistPlayerID="default"
ingest_profile=""
key="0000000000000"
asset_integration_path="/content/dam/brightcove_assets"
defPlaylistPlayerKey=""
playersstore="/content/brightcovetools/players"
defVideoPlayerKey=""`

**Comment by hngrylobster** [comment]
What happens when you remove the "90abfe45-4b0c-41b0-b22b-b0ee9b79415f" part of the *.config file?

**Comment by stiegjo** [comment]
Thanks - that fixed it.
