### ISSUE TITLE
Content Security Policy Issue

### ISSUE THREAD

**Issue by RKcrbgf** [brightcove/Adobe-AEM-Brightcove-Connector#68]
After removing **'unsafe-eval '** from our CSP directive ,  we are facing the following issue for pages where **Brightcove Video player**  
 component is configured -- 
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script .
We are using **Brightcove 6.1.3-cloud AEM Connector** .

Source is shown in below screenshots -> 

![image](https://github.com/brightcove/Adobe-AEM-Brightcove-Connector/assets/164872342/0abbb57f-3680-4f05-aec2-37bf0668176e)
![image](https://github.com/brightcove/Adobe-AEM-Brightcove-Connector/assets/164872342/7080c3b3-266a-494a-8798-f6ca6d65d04a)

Could you please look into all possible CSP issues with Brightcove - AEM connector and provide solution ASAP ?

**Comment by RKcrbgf** [comment]
@hngrylobster , could you please take a look on this issue ?

**Comment by dcolvin** [comment]
@RKcrbgf I have fixed this and is in the latest release 6.1.4(Cloud) https://github.com/brightcove/Adobe-AEM-Brightcove-Connector/releases/tag/6.1.4

**Comment by RKcrbgf** [comment]
Thank you @dcolvin  for the fix . 👍
